stages:
#  - lint
  - SCA
#  - Build

#build:
#  stage: Build
#  tags:
#    - app
#  services:
#    - docker:latest
#  script:
#     - "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}"
#     - "docker build -t ${CI_REGISTRY_USER}/coffee-shop:latest ."
#     - "docker push ${CI_REGISTRY_USER}/coffee-shop:latest"

owasp_dependency_check:
  stage: SCA
  tags:
    - app
  script:
    - >
      docker run --rm -e user=$USER -u $(id -u ${USER}):$(id -g ${USER}) --volume $(pwd):/src:z 
      --volume /vagrant/:/report:z owasp/dependency-check:latest --scan /src --format "ALL" --project "Coffee-Shop" 
        --out /report

  allow_failure: true

#lint:
#  stage: lint
#  tags:
#    - app
#  script:
#    - npm install  
#    - npm run lint
