stages:
  - Validate project
  - SAST & SCA
  - Build and Push Docker Image
  - Container Scan
  - Deploy on app machine

lint:
  stage: Validate project
  tags:
    - app-proxmox-sgoncalves
  script:
    - npm install eslint eslint-config-standard-with-typescript eslint-plugin-import eslint-plugin-node eslint-plugin-promise typescript@4.4.2 @typescript-eslint/eslint-plugin @typescript-eslint/parser
    - npm run lint

sast:
  stage: SAST & SCA
  tags:
    - app-proxmox-sgoncalves
  script:
    - '/usr/local/bin/horusec start -p . -a ${HORUSEC_API_KEY} -u http://devsecops.labs.devsecops:8000 -G true --enable-git-history=true -w'

build:
  stage: Build and Push Docker Image
  tags:
    - app-proxmox-sgoncalves
  services:
    - docker:latest
  script:
     - "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}"
     - "docker build -t ${CI_REGISTRY_USER}/coffee-shop:latest ."
     - "docker push ${CI_REGISTRY_USER}/coffee-shop:latest"

deploy:
  stage: Deploy on app machine
  tags:
    - app-proxmox-sgoncalves
  script:
     - "docker rm -f coffee-shop-app 2> /dev/null"
     - "docker pull ${CI_REGISTRY_USER}/coffee-shop:latest"
     - "docker run -d -p 3000:3000 --name coffee-shop-app ${CI_REGISTRY_USER}/coffee-shop"

trivy:
  stage: Container Scan
  image: docker:stable-git
  before_script:
    - docker build -t trivy-ci-test . 
    - wget https://github.com/aquasecurity/trivy/releases/download/v0.1.6/trivy_0.1.6_Linux-64bit.tar.gz
    - tar zxvf trivy_0.1.6_Linux-64bit.tar.gz
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - ./trivy --exit-code 0 --severity HIGH --no-progress --auto-refresh trivy-ci-test
    - ./trivy — exit-code 1 — severity CRITICAL — no-progress — auto-refresh trivy-ci-test

