stages:
  - lint
  - SCA
  - Build

build:
  stage: Build
  tags:
    - app
  services:
    - docker:latest
  script:
     - "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}"
     - "docker build -t ${CI_REGISTRY_USER}/coffee-shop:latest ."
     - "docker push ${CI_REGISTRY_USER}/coffee-shop:latest"

owasp_dependency_check:
  image: owasp/dependency-check
  stage: SCA
  script: 
    - --scan "./" --format ALL --project "$CI_PROJECT_NAME" --out ./
  allow_failure: true
  artifacts:
    when: always
    paths:
      - "./dependency-check-report.html"
      - "./dependency-check-report.json"

lint:
  stage: lint
  script:
    - npm install  
    - npm run build
    - npm run prettier:check
    - npm run lint:check
