stages:
  - SCA

build:
  stage: Build
  tags:
    - app
  services:
    - docker:latest
  script:
     - "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}"
     - "docker build -t ${CI_REGISTRY_USER}/coffee-shop:latest ."
     - "docker push ${CI_REGISTRY_USER}/coffee-shop:latest"

owasp_dependency_check:
  stage: SCA
  tags:
    - app
  script:
    - >
      docker run --volume $(pwd):/project --volume $(pwd)/.owasp:/usr/share/dependency-check/data 
      owasp/dependency-check:6.4.1 --scan '/project' --failOnCVSS 0 --format "ALL" --out "/project/tests/reports"
  allow_failure: true

lint:
  stage: lint
  tags:
    - app
  script:
    - npm install  
    - npm run lint
