stages:
  - OWASP Dependency Check
  - Build


build:
  stage: Build
  script:
     - "docker build -t ${CI_REGISTRY_USER}/coffee-shop:latest ."
     - "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}"
     - "docker push ${CI_REGISTRY_USER}/coffee-shop:latest"

owasp_dependency_check:
  stage: OWASP Dependency Check
  script: 
    - npm install -D owasp-dependency-check
    - owasp-dependency-check --project "$CI_PROJECT_NAME" --format ALL --failOnCVSS 0 
  allow_failure: true
  artifacts:
    when: always
    paths:
      - "./dependency-check-report.html"
      - "./dependency-check-report.json"



