stages:
  - Validate project
  - SAST
  - SCA
  - Build and Push Docker Image
  - Container Scan
  - Deploy on app machine

lint:
  stage: Validate project
  tags:
    - app-proxmox-sgoncalves
  script:
    - npm install eslint eslint-config-standard-with-typescript eslint-plugin-import eslint-plugin-node eslint-plugin-promise typescript@4.4.2 @typescript-eslint/eslint-plugin @typescript-eslint/parser
    - npm run lint

sast:
  stage: SAST & SCA
  tags:
    - app-proxmox-sgoncalves
  script:
    - '/usr/local/bin/horusec start -p . -a ${HORUSEC_API_KEY} -u http://devsecops.labs.devsecops:8000 -G true --enable-git-history=true -w'

build:
  stage: Build and Push Docker Image
  tags:
    - app-proxmox-sgoncalves
  services:
    - docker:latest
  script:
     - "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}"
     - "docker build -t ${CI_REGISTRY_USER}/coffee-shop:latest ."
     - "docker push ${CI_REGISTRY_USER}/coffee-shop:latest"

deploy:
  stage: Deploy on app machine
  tags:
    - app-proxmox-sgoncalves
  script:
     - "docker rm -f coffee-shop-app 2> /dev/null"
     - "docker pull ${CI_REGISTRY_USER}/coffee-shop:latest"
     - "docker run -d -p 3000:3000 --name coffee-shop-app ${CI_REGISTRY_USER}/coffee-shop"

trivy:
  stage: Container Scan
  tags:
    - app-proxmox-sgoncalves
  script:
    - "/usr/local/bin/trivy image --severity HIGH --format table --output scan.txt ${CI_REGISTRY_USER}/coffee-shop:latest"

dependencycheck:
    stage: SCA
    image:
        name: owasp/dependency-check
        entrypoint: [""]
#    before_script:
#        - mkdir data
#        - mkdir dependency-check
    script:
        - /usr/share/dependency-check/bin/dependency-check.sh --project coffee-shop --out . --scan . --enableExperimental --failOnCVSS 7    

