stages:
  - OWASP Dependency Check
  - Build


build:
  stage: Build
  services:
    - docker:latest
  script:
     - "docker build -t ${CI_REGISTRY_USER}/coffee-shop:latest ."
     - "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}"
     - "docker push ${CI_REGISTRY_USER}/coffee-shop:latest"

owasp_dependency_check:
  image: owasp/dependency-check
  stage: OWASP Dependency Check
  script: 
    - --scan "./" --format ALL --project "$CI_PROJECT_NAME" --out ./
  allow_failure: true
  artifacts:
    when: always
    paths:
      - "./dependency-check-report.html"
      - "./dependency-check-report.json"



