stages:
  #- Validate project
  - SCA
  #- Build and Push Docker Image
  #- Deploy on app machine

build:
  stage: Build and Push Docker Image
  tags:
    - app
  services:
    - docker:latest
  script:
     - "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}"
     - "docker build -t ${CI_REGISTRY_USER}/coffee-shop:latest ."
     - "docker push ${CI_REGISTRY_USER}/coffee-shop:latest"

owasp_dependency_check:
  stage: SCA
  tags:
    - app
  image:
    name: owasp/dependency-check
    entrypoint: [""]
  dependencies:
    - lint
  script:
    - /usr/share/dependency-check/bin/dependency-check.sh --project coffe-shop --out . --scan . --enableExperimental --failOnCVSS 7
  allow_failure: true

lint:
  stage: Validate project
  tags:
    - app
  script:
    - npm install
    - npm run lint

deploy:
  stage: Deploy on app machine
  tags:
    - app
  script:
     - "docker rm -f coffee-shop-app 2> /dev/null"
     - "docker pull ${CI_REGISTRY_USER}/coffee-shop:latest"
     - "docker run -d -p 3000:3000 --name coffee-shop-app ${CI_REGISTRY_USER}/coffee-shop"
