---
version: "3.7"
services:
  traefik:
    image: "traefik:v2.8"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.coffeeshop.address=:80"
    ports:
      - "80:80"
      - "8081:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
...