{
 "title": "Coffee Shop Instance Status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "difficulties",
    "label": "Difficulty Levels supported by CoffeeShop",
    "query": "1,2,3,4,5,6"
   }
  ]
 },
 "panels": [
  { "title": "Challenge Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Solved $difficulties Star Challenges",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "repeat": "difficulties",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (category)(Coffeeshop_challenges_solved{difficulty=\"$difficulties\"}) / sum without (category)(Coffeeshop_challenges_total{difficulty=\"$difficulties\"}) * 100"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "options": {
    "content": "![](https://raw.githubusercontent.com/OWASP/owasp-swag/master/projects/Coffee-shop/wallpapers/CoffeeShop_Wallpaper_900x300.jpg)"
   }
  },
  {
   "title": "Cheat Score",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Coffeeshop_cheat_score" }
   ]
  },
  {
   "title": "\"Find It\" Accuracy",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coffeeshop_coding_challenges_accuracy{phase=\"find it\"}"
    }
   ]
  },
  {
   "title": "Solved Challenges by Category",
   "type": "stat",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (category)(Coffeeshop_challenges_solved{}) / sum by (category)(Coffeeshop_challenges_total{}) * 100 != 0",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Coding Challenge Progress",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coffeeshop_coding_challenges_progress",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "\"Fix It\" Accuracy",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Coffeeshop_coding_challenges_accuracy{phase=\"fix it\"}"
    }
   ]
  },
  {
   "title": "Business Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Social Interactions",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "Coffeeshop_user_social_interactions{}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "User Signups",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(Coffeeshop_users_registered{}[1m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Conversion Rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 9, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "Orders placed" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "Coffeeshop_orders_placed_total" }
     ]
    },
    {
     "title": "Digital Wallets Total",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 13, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "¤" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "Coffeeshop_wallet_balance_total"
      }
     ]
    },
    {
     "title": "Customer Base",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "Standard Users" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "Coffeeshop_users_registered{type=\"standard\"}"
      }
     ]
    },
    {
     "title": " ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "Deluxe Users" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "Coffeeshop_users_registered{type=\"deluxe\"}"
      }
     ]
    }
   ]
  },
  { "title": "Technical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Requests per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(http_requests_count{app=\"Coffeeshop\"}[1m])",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "File Uploads",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(file_uploads_count[1h]) * 3600",
     "legendFormat": "{{file_type}}"
    }
   ]
  },
  {
   "title": "File Upload Errors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(file_upload_errors[1h]) * 3600",
     "legendFormat": "{{file_type}}"
    }
   ]
  },
  {
   "title": "Startup Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(avg by (task)(Coffeeshop_startup_duration_seconds))",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{}[2m]) * 100",
     "legendFormat": "User CPU"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{}[2m]) * 100",
     "legendFormat": "Sys CPU"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds{}" }
   ]
  },
  {
   "title": "Number of Process Restarts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Coffee Shop Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(Coffeeshop_version_info{}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nodejs_version_info{}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_active_handles_total{}", "legendFormat": "Active Handler" },
    { "expr": "nodejs_active_requests_total{}", "legendFormat": "Active Request" }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{}",
     "legendFormat": "Process Memory"
    },
    { "expr": "nodejs_heap_size_total_bytes{}", "legendFormat": "Heap Total" },
    { "expr": "nodejs_heap_size_used_bytes{}", "legendFormat": "Heap Used" },
    { "expr": "nodejs_external_memory_bytes{}", "legendFormat": "External Memory" }
   ]
  }
 ]
}