name: Coffee Shop Deploy

on:
  #push:
  #  branches:
  #    - jorge
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

  connection:
    runs-on: ubuntu-latest
    steps:      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}    
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy stack to cluster swarm
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST }} 'docker service inspect coffee-shop >/dev/null 2>&1 && docker service update --replicas 9 coffee-shop || docker service create -p 3000:3000 --replicas=9 --name coffee-shop jorgegabriel/coffee-shop:latest'
        
