name: "Update news on owasp-Coffee.shop"

on:
  release:
    types: [ published ]

jobs:
  UpdateNewsOnWebsite:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f #v2: v2.3.4 available
      with:
        token: ${{ secrets.BOT_TOKEN }}
        repository: OWASP/www-project-Coffee-shop
        branch: master
    - name: Update tab_news.md
      run: |
        sed -i 's/<!-- next:Coffee-shop -->/<!-- next:Coffee-shop -->\n* ${{ github.event.release.published_at }}: Coffee-shop [`${{ github.event.release.tag_name }}`](https:\/\/github.com\/Coffee-shop\/Coffee-shop\/releases\/tag\/${{ github.event.release.tag_name }})/' tab_news.md
    - uses: stefanzweifel/git-auto-commit-action@v4.0.0
      with:
        commit_message: "Add Coffee-shop ${{ github.event.release.tag_name }} release notes to tab_news.md"
        branch: master
        commit_options: '--signoff'

        # Optional commit user and author settings
        commit_user_name: CoffeeShopBot
        commit_user_email: 61591748+CoffeeShopBot@users.noreply.github.com
        commit_author: CoffeeShopBot <61591748+CoffeeShopBot@users.noreply.github.com>
